version: '3'

services:
  bt-joiner:
    image: hub.foundries.io/bt-joiner:latest
    privileged: true
    read_only: true
    restart: always
    network_mode: "host"
    tmpfs:
      - /run
      - /var/lock
      - /var/log
  cf-proxy-coap-http:
    image: hub.foundries.io/cf-proxy-coap-http:latest
    read_only: true
    restart: always
    network_mode: "host"
  nginx-coap-proxy:
    image: hub.foundries.io/nginx:latest
    command: nginx-debug -g 'daemon off;'
    read_only: true
    restart: always
    network_mode: "host"
    tmpfs:
      - /var/run
    volumes:
      - /home/osf/fio-gateway/nginx-lwm2m.conf:/etc/nginx/nginx.conf
  mosquitto:
    image: hub.foundries.io/mosquitto:latest
    read_only: true
    restart: always
    network_mode: "host"
    volumes:
      - /home/osf/fio-gateway/mosquitto.conf:/etc/mosquitto/conf.d/mosquitto.conf
  nginx-http-proxy:
    image: hub.foundries.io/nginx:latest
    command: nginx-debug -g 'daemon off;'
    read_only: true
    restart: always
    network_mode: "host"
    tmpfs:
      - /var/run
      - /var/cache/nginx
    volumes:
      - /home/osf/fio-gateway/nginx-http-proxy.conf:/etc/nginx/nginx.conf
